on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: run build project
      run: cd project && go build . 

  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - id: run-coverage-action
      uses: mayusGomez/golang-cover-action@v2
      with:
        project-folder: 'project'
        pakage-to-check: './sender'
        min-coverage: '40'

